spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_challenge
    username: doodle
    password: d00D13
    driverClassName: org.postgresql.Driver
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false